### ISSUE TITLE
Usage with CMake

### ISSUE THREAD

**Issue by JoshuaBehrens** [yue/help#2]
I'd like to use this library with CMake. The shipped CMakeLists.txt is helpful but the distribution lacks a find_package file. It is difficult to setup a build system for different platforms. It also seems like it is unwanted to distribute yue for CMake as ng and ninja are primarly used.

Are there any plans to improve CMake usage as it is shipped with a CMakeFiles.txt? Otherwise a CMakeFiles.txt for build libyue is appreciated.

**Comment by zcbenz** [comment]
The shipped `CMakeLists.txt` is used to build with the prebuilt static libraries, it does not build the sources of libyue so it does not involve gn and ninja. As for the `find_package` package, I believe most Linux distributions have it in their package managers, honestly I don't know what can I do if your distribution does not have it.  

As for a CMakeFiles.txt building libyue itself, I'm afraid it is too much work and I will never do it, my plan is to  make a standalone version of gn so users can easily use gn for their projects.
